-- Seed data for Project Alpha
BEGIN;

TRUNCATE TABLE ticket_tags RESTART IDENTITY CASCADE;
TRUNCATE TABLE tickets RESTART IDENTITY CASCADE;
TRUNCATE TABLE tags RESTART IDENTITY CASCADE;

INSERT INTO tags (id, name, created_at) VALUES
    (1, 'frontend', NOW() - INTERVAL '40 day'),
    (2, 'backend', NOW() - INTERVAL '39 day'),
    (3, 'database', NOW() - INTERVAL '38 day'),
    (4, 'devops', NOW() - INTERVAL '37 day'),
    (5, 'testing', NOW() - INTERVAL '36 day'),
    (6, 'performance', NOW() - INTERVAL '35 day'),
    (7, 'usability', NOW() - INTERVAL '34 day'),
    (8, 'planning', NOW() - INTERVAL '33 day'),
    (9, 'documentation', NOW() - INTERVAL '32 day'),
    (10, 'bug', NOW() - INTERVAL '31 day'),
    (11, 'enhancement', NOW() - INTERVAL '30 day'),
    (12, 'api', NOW() - INTERVAL '29 day'),
    (13, 'design', NOW() - INTERVAL '28 day'),
    (14, 'reminder', NOW() - INTERVAL '27 day'),
    (15, 'analytics', NOW() - INTERVAL '26 day'),
    (16, 'notification', NOW() - INTERVAL '25 day'),
    (17, 'integration', NOW() - INTERVAL '24 day'),
    (18, 'sync', NOW() - INTERVAL '23 day'),
    (19, 'security', NOW() - INTERVAL '22 day'),
    (20, 'monitoring', NOW() - INTERVAL '21 day');

INSERT INTO tickets (id, title, description, priority, status, created_at, updated_at) VALUES
    (1, 'Compile product requirement backlog', 'Summarize user stories and map them into actionable backlog items.', 'high', 'completed', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 1, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 1),
    (2, 'Define MVP scope checklist', 'Clarify minimum viable feature set with stakeholders.', 'medium', 'completed', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 2, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 2),
    (3, 'Design ticket database schema', 'Define tables, relationships, and constraints for ticket storage.', 'low', 'completed', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 3, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 3),
    (4, 'Bootstrap FastAPI service project', 'Create FastAPI project structure with configuration scaffolding.', 'high', 'completed', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 4, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 4),
    (5, 'Implement ticket create endpoint', 'Expose POST /api/tickets with validation and persistence.', 'medium', 'completed', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 5, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 5),
    (6, 'Implement ticket update endpoint', 'Support PUT /api/tickets/{id} to update core fields.', 'low', 'completed', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 6, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 6),
    (7, 'Implement ticket delete endpoint', 'Allow DELETE /api/tickets/{id} to remove records safely.', 'high', 'completed', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 7, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 7),
    (8, 'Implement ticket list endpoint', 'Return paginated ticket lists with filters applied.', 'medium', 'completed', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 8, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 8),
    (9, 'Build tag assignment endpoint', 'Enable adding and removing tags for a specific ticket.', 'low', 'completed', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 9, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 9),
    (10, 'Implement ticket search endpoint', 'Implement fuzzy search by title with pagination support.', 'high', 'completed', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 10, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 10),
    (11, 'Write API reference documentation', 'Document all REST endpoints with request and response samples.', 'medium', 'completed', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 11, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 11),
    (12, 'Configure Alembic migrations', 'Configure Alembic environment and baseline migration scripts.', 'low', 'completed', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 12, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 12),
    (13, 'Add backend unit test suite', 'Add pytest coverage for service and router layers.', 'high', 'completed', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 13, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 13),
    (14, 'Initialize frontend project scaffold', 'Initialize Vite + React codebase with essential tooling.', 'medium', 'completed', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 14, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 14),
    (15, 'Design dashboard layout wireframe', 'Draft dashboard wireframe covering panels and navigation.', 'low', 'completed', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 15, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 15),
    (16, 'Develop ticket list component', 'Render adaptive ticket list with sorting and empty states.', 'high', 'pending', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 16, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 16),
    (17, 'Build ticket dialog component', 'Create modal dialog for creating and editing tickets.', 'medium', 'pending', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 17, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 17),
    (18, 'Create tag filter sidebar', 'Build sidebar filter UI for tag selection and quick filters.', 'low', 'pending', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 18, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 18),
    (19, 'Add search input interactions', 'Implement search bar with debounce and clear actions.', 'high', 'pending', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 19, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 19),
    (20, 'Implement status toggle behavior', 'Toggle ticket completion state with optimistic updates.', 'medium', 'pending', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 20, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 20),
    (21, 'Integrate frontend with backend API', 'Wire API client hooks and confirm data flow end-to-end.', 'low', 'pending', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 21, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 21),
    (22, 'Draft user getting started guide', 'Write onboarding instructions for developers and reviewers.', 'high', 'pending', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 22, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 22),
    (23, 'Prepare deployment runbook', 'Describe deploy steps for local and staging environments.', 'medium', 'pending', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 23, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 23),
    (24, 'Seed demo dataset for review', 'Prepare sample tickets and tags for demo showcases.', 'low', 'pending', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 24, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 24),
    (25, 'Optimize database indexes', 'Add indexes to optimize frequent query patterns.', 'high', 'pending', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 25, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 25),
    (26, 'Develop pagination component', 'Implement reusable pagination component with keyboard support.', 'medium', 'pending', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 26, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 26),
    (27, 'Implement status filter controls', 'Add status filter controls to dashboard toolbar.', 'low', 'pending', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 27, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 27),
    (28, 'Add priority badge styling', 'Style priority badges with accessible color contrast.', 'high', 'pending', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 28, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 28),
    (29, 'Integrate toast notification system', 'Hook toast notifications for success and error states.', 'medium', 'pending', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 29, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 29),
    (30, 'Configure ESLint rule set', 'Set up ESLint with project-specific rule overrides.', 'low', 'pending', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 30, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 30),
    (31, 'Configure Prettier formatting', 'Configure Prettier formatting and editor integration.', 'high', 'completed', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 31, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 31),
    (32, 'Set up pytest coverage reporting', 'Collect coverage metrics and enforce minimum thresholds.', 'medium', 'completed', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 32, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 32),
    (33, 'Create CI workflow pipeline', 'Create CI pipeline for lint, test, and build jobs.', 'low', 'completed', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 33, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 33),
    (34, 'Implement error boundary page', 'Render friendly error boundary page for runtime failures.', 'high', 'pending', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 34, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 34),
    (35, 'Add empty state illustrations', 'Show engaging empty state messages for list views.', 'medium', 'pending', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 35, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 35),
    (36, 'Add loading skeleton components', 'Display skeleton loaders during network requests.', 'low', 'pending', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 36, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 36),
    (37, 'Implement batch delete API endpoint', 'Implement bulk delete endpoint with transactional safety.', 'high', 'pending', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 37, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 37),
    (38, 'Build batch delete frontend UX', 'Build bulk delete selection flow on the frontend.', 'medium', 'pending', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 38, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 38),
    (39, 'Author E2E test scripts', 'Write Playwright scenarios covering critical flows.', 'low', 'pending', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 39, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 39),
    (40, 'Curate troubleshooting FAQ', 'Draft FAQ to address recurring troubleshooting questions.', 'high', 'completed', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 40, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 40),
    (41, 'Collect user feedback responses', 'Gather beta feedback and categorize improvement themes.', 'medium', 'pending', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 41, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 41),
    (42, 'Analyze performance bottlenecks', 'Profile API performance and record bottleneck notes.', 'low', 'pending', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 42, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 42),
    (43, 'Plan next phase roadmap', 'Outline roadmap items for next milestone planning.', 'high', 'pending', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 43, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 43),
    (44, 'Design notification strategy', 'Map notification touchpoints and delivery channels.', 'medium', 'pending', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 44, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 44),
    (45, 'Assemble release readiness checklist', 'Assemble checklist to verify release readiness criteria.', 'low', 'pending', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 45, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 45),
    (46, 'Security vulnerability review', 'Assess system for common security weaknesses.', 'high', 'completed', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 46, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 46),
    (47, 'Audit logging requirements', 'List required audit log events and retention rules.', 'medium', 'completed', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 47, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 47),
    (48, 'Document logging conventions', 'Document logging format, levels, and aggregation strategy.', 'low', 'completed', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 48, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 48),
    (49, 'Set up monitoring alerts', 'Set up monitoring dashboards and alert thresholds.', 'high', 'completed', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 49, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 49),
    (50, 'Run final release acceptance', 'Conduct final acceptance review before rollout.', 'medium', 'completed', NOW() - INTERVAL '60 day' + INTERVAL '1 day' * 50, NOW() - INTERVAL '30 day' + INTERVAL '1 day' * 50);

INSERT INTO ticket_tags (ticket_id, tag_id, created_at) VALUES
    (1, 8, NOW()), (1, 9, NOW()),
    (2, 8, NOW()), (2, 7, NOW()),
    (3, 2, NOW()), (3, 3, NOW()),
    (4, 2, NOW()), (4, 12, NOW()),
    (5, 2, NOW()), (5, 12, NOW()),
    (6, 2, NOW()), (6, 12, NOW()),
    (7, 2, NOW()), (7, 12, NOW()),
    (8, 2, NOW()), (8, 12, NOW()),
    (9, 2, NOW()), (9, 11, NOW()),
    (10, 2, NOW()), (10, 12, NOW()),
    (11, 9, NOW()), (11, 8, NOW()),
    (12, 2, NOW()), (12, 3, NOW()),
    (13, 5, NOW()), (13, 2, NOW()),
    (14, 1, NOW()), (14, 13, NOW()),
    (15, 1, NOW()), (15, 13, NOW()),
    (16, 1, NOW()), (16, 13, NOW()),
    (17, 1, NOW()), (17, 13, NOW()),
    (18, 1, NOW()), (18, 11, NOW()),
    (19, 1, NOW()), (19, 11, NOW()),
    (20, 1, NOW()), (20, 7, NOW()),
    (21, 17, NOW()), (21, 2, NOW()),
    (22, 9, NOW()), (22, 8, NOW()),
    (23, 4, NOW()), (23, 9, NOW()),
    (24, 9, NOW()), (24, 8, NOW()),
    (25, 3, NOW()), (25, 6, NOW()),
    (26, 1, NOW()), (26, 13, NOW()),
    (27, 7, NOW()), (27, 11, NOW()),
    (28, 7, NOW()), (28, 11, NOW()),
    (29, 16, NOW()), (29, 14, NOW()),
    (30, 1, NOW()), (30, 13, NOW()),
    (31, 1, NOW()), (31, 13, NOW()),
    (32, 5, NOW()), (32, 11, NOW()),
    (33, 4, NOW()), (33, 5, NOW()),
    (34, 7, NOW()), (34, 11, NOW()),
    (35, 7, NOW()), (35, 13, NOW()),
    (36, 7, NOW()), (36, 13, NOW()),
    (37, 2, NOW()), (37, 11, NOW()),
    (38, 1, NOW()), (38, 11, NOW()),
    (39, 5, NOW()), (39, 17, NOW()),
    (40, 9, NOW()), (40, 14, NOW()),
    (41, 7, NOW()), (41, 14, NOW()),
    (42, 6, NOW()), (42, 15, NOW()),
    (43, 8, NOW()), (43, 11, NOW()),
    (44, 16, NOW()), (44, 14, NOW()),
    (45, 4, NOW()), (45, 17, NOW()),
    (46, 19, NOW()), (46, 5, NOW()),
    (47, 16, NOW()), (47, 17, NOW()),
    (48, 9, NOW()), (48, 7, NOW()),
    (49, 20, NOW()), (49, 4, NOW()),
    (50, 8, NOW()), (50, 7, NOW());

SELECT setval('tags_id_seq', 20, true);
SELECT setval('tickets_id_seq', 50, true);
SELECT setval('ticket_tags_id_seq', COALESCE((SELECT MAX(id) FROM ticket_tags), 0), true);

COMMIT;
